name: Builds

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      - name: Get dependencies
        run: flutter pub get

      - name: Start release build
        run: flutter build linux --release

      - name: Zip Assets
        run: |
          cd build/linux/x64/release/bundle/
          zip -r Linux-Bundle.zip .

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          files: |
            Linux-Bundle.zip
          draft: true

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Fix pods
        run: cd macos/ && pod install && cd ../

      - name: Start release build
        run: flutter build macos --release

      - name: Zip Assets
        run: |
          cd build/macos/Build/Products/Release/
          zip -r MacOS-Bundle.zip shadow_queue.app

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          files: |
            MacOS-Bundle.zip
          draft: true

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Start release build
        run: flutter build windows --release

      - name: Zip Assets
        run: |
          pushd .
          cd build/windows/runner/Release/
          Compress-Archive * Windows-Bundle.zip
          popd
          mv build/windows/runner/Release/Windows-Bundle.zip .

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          files: |
            Windows-Bundle.zip
          draft: true
